# CouchDb clients config
# BASE_URL: URL of the `CouchDB` or [replication backend](https://github.com/Aam-Digital/replication-backend)
# TARGET_DATABASE: CouchDb database name
COUCH_DB_CLIENT:
  NOTIFICATION:
    BASE_URL: http://localhost:5984
    TARGET_DATABASE: notification-webhook
  APP:
    BASE_URL: http://localhost:5984
    TARGET_DATABASE: app
  REPORT_CALCULATION:
    BASE_URL: http://localhost:5984
    TARGET_DATABASE: report-calculation

# CouchDb SQS client config
# BASE_URL: URL of the SQS
# SCHEMA_DESIGN_CONFIG: database ID of the document which holds the SQS schema (default `/app/_design/sqlite:config`)
QUERY:
  SCHEMA_DESIGN_CONFIG: /_design/sqlite:config
  SQS_CLIENT:
    BASE_URL: http://localhost:4984
    TARGET_DATABASE: app

REPORT_CHANGES_POLL_INTERVAL: 10000

OPENID_CONFIGURATION: http://localhost:8080/realms/dummy-realm/.well-known/openid-configuration

# Logger Configuration
# values can be overwritten in .env file

SENTRY:
  ENABLED: false
  INSTANCE_NAME: local-development # can be personalised in .env -> local-development-<your-name>
  ENVIRONMENT: local # local | development | production
  DSN: ''
