openapi: 3.0.3
info:
  title: Aam Digital - Report API
  description: |-
    todo
  version: 1.0.0-draft.3
servers:
  - url: https://dev.aam-digital.com/api/v1
tags:
  - name: report
paths:
  /report:
    get:
      tags:
        - report
      summary: Return list of available Reports
      responses:
        200:
          description: List of all available Reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'
  #    post:
  #      tags:
  #        - report
  #      summary: Create a new Report
  #      responses:
  #        default:
  #          description: response

  /report/{reportId}:
    get:
      tags:
        - report
      summary: Return report by ID
      parameters:
        - in: path
          name: reportId
          schema:
            type: string
          required: true
      responses:
        200:
          description: List of all available Reports
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'

  /report/{reportId}/calculation:
    post:
      tags:
        - report
      summary: Trigger a new report calculation run
      parameters:
        - in: path
          name: reportId
          schema:
            type: string
          required: true
        - in: query
          name: from
          schema:
            type: string
            format: date
            required: true
        - in: query
          name: to
          schema:
            type: string
            format: date
            required: true
      responses:
        200:
          description: Return calculation identifier
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  type:
                    type: string
                    example: "ReportCalculation"

  /report-calculation/report/{reportId}:
    get:
      tags:
        - report
      summary: Return all report calculations for a report
      parameters:
        - in: path
          name: reportId
          schema:
            type: string
          required: true
      responses:
        200:
          description: Successful report data response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportCalculation'

  /report-calculation/{calculationId}:
    get:
      tags:
        - report
      summary: Return metadata for a report calculation
      parameters:
        - in: path
          name: calculationId
          schema:
            type: string
          required: true
      responses:
        200:
          description: Successful report data response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReportCalculation'

  /report-calculation/{calculationId}/data:
    get:
      tags:
        - report
      summary: Fetch actual report data for a specific calculation
      parameters:
        - in: path
          name: calculationId
          schema:
            type: string
          required: true
      responses:
        200:
          description: successful report data response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportData'
            application/xml:
              schema:
                $ref: '#/components/schemas/ReportData'
        404:
          description: report data is not available yet

components:
  schemas:
    Report:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: report_all_course_members
        #        last_run:
        #          type: string
        #          format: date
        calculationPending:
          type: boolean
        schema:
          $ref: '#/components/schemas/ReportSchema'

    ReportSchema:
      type: object
      properties:
        fields:
          type: array

    ReportCalculation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        start_date:
          type: string
          example: date
        end_date:
          type: string
          example: date
          nullable: true
        status:
          type: string
          description: Current status of the run
          enum:
            - PENDING
            - RUNNING
            - FINISHED_SUCCESS
            - FINISHED_ERROR

    ReportData:
      type: object
      properties:
        reportId:
          type: string
          format: uuid
        data:
          type: object

  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://keycloak.aam-digital.com/realms/dev/.well-known/openid-configuration

security:
  - openId:
      - reports_read
      - reports_write

