@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor user as "User"
participant ad as "AD System (FE/BE)"
participant adauth as "AD Auth-System"
participant 3rd as "Third Party Backend"

user -> ad: Sign in into Aam Digital service
ad -> adauth: Auth request
adauth --> adauth: Verify credentials
adauth --> adauth: generate token
adauth -> ad: return token
user -> ad: create new client integration (integration-api)
...
user -> 3rd: start "sign-in with aam" process
3rd <--> adauth: fetch user related token
3rd -> ad: fetch secret for client-integration with user token
3rd --> 3rd: store client-id and client-secret securely
...
3rd -> adauth: create system access token with stored credentials
3rd -> ad: use system token on aam digital apis
...

@enduml
